#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#   título.py
#  
#   2021 <https://github.com/Prolgu>
#  
#  


def main(args):
    return 0

if __name__ == '__main__':
    import sys
    sys.exit(main(sys.argv))
