-- NOTE: asdasd
-- require('config.impatient')
require('config.colors')
-- require('config.signs')
require('config.theme')
require('config.globals')
require('config.luline')
-- require('config.tree')
require('config.lsp')
require('config.completion')
-- require('config.cmp')
require('config.lsnippets')
require('config.todo')
require('config.autopairs')
require('config.indent')
require('config.toggle')
require('config.telescope')
require('config.bufferline')
require('config.symbols')
require('config.nvim-tree')
require('config.dbui')
require('config.glow')
-- require('config.mason')
require('config.hlargs')
