#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width        2
bspc config window_gap          3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

# bspc config pointer_follows_focus false; \
# bspc node -f "$direction"; \
# bspc config pointer_follows_focus true


# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^5'
bspc rule -a firefox desktop='^3'
bspc rule -a Thunar desktop='^4' follow=on
# ========== ========== ==========
bspc rule -a Emacs desktop='^1' state=tiled follow=on
# bspc rule -a Postman desktop='^2' follow=on
# bspc rule -a VSCodium desktop='^2' follow=on
# bspc rule -a Mysql-workbench-bin desktop='^2' follow=on
# ========== ========== ==========
bspc rule -a Zathura state=tiled
bspc rule -a St state=floating follow=on
bspc rule -a Xterm state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol state=floating
bspc rule -a TelegramDesktop desktop='^5' follow=on
# bspc rule -a Helm state=float
# bspc rule -a Slack desktop='^5' follow=on
bspc rule -a "Apache NetBeans IDE 14" desktop='^2' follow=on
bspc rule -a NetBeans desktop='^2' follow=on
# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
sh ~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/
# Picom
# picom -CGb &
# picom &
# Network Applet
nm-applet --indicator &
# fix Java
wmname LG3D &

# Cursor
xsetroot -cursor_name left_ptr &
xset r rate 190 45 &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh &

# st on start
# st -e emacs -nw
# st
# sleep 20 &
# emacsclient -nc &
~/.scripts/daemon-check.sh

