#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 

# bspc config top_padding 20

bspc config border_width        1
bspc config window_gap          5
bspc config border_radius       8

bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config initial_polarity     second_child
# bspc config automatic_scheme     spiral
bspc config center_pseudo_tiled  true

bspc rule -a firefox desktop='^2'
bspc rule -a Luakit desktop='^1'
bspc rule -a Emacs desktop='^1' follow=on
bspc rule -a Twitch desktop='^3'
bspc rule -a VSCodium desktop='^5'
bspc rule -a TelegramDesktop desktop='^4' follow=on
bspc rule -a Thunar desktop='^5'


bspc rule -a kitty state=floating follow=on rectangle 800x700+0+0 center=true
bspc rule -a Blueberry.py state=floating follow=on  center=true
bspc rule -a Pavucontrol state=floating follow=on  center=true
# bspc rule -a \* rectangle 800x600+0+0 center=true


bspc rule -a Zathura state=tiled follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focused_border_color "#45fda0"
bspc config normal_border_color "#353b45"
bspc config presel_feedback_color "#839496"

# Autostart
mpd;/usr/bin/dunst &
xset s 480 dpms 600 600 600 &
nitrogen --restore &
blueberry-tray;nm-applet &
picom & 
sleep 5 && st -e tmux new-session -A -s ws &
killall polybar; polybar -r example & 
sleep 1 && polybar -r bottom &
