#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 

# bspc config top_padding 20

bspc config border_width        1
bspc config window_gap          5
bspc config border_radius       8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a Twitch desktop='^3'

bspc rule -a Thunar desktop='^5'

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focused_border_color "#3e4451"
bspc config normal_border_color "#353b45"

# Autostart
mpd;/usr/bin/dunst &
xset s 480 dpms 600 600 600 &
nitrogen --restore &
blueberry-tray;nm-applet &
picom &
killall polybar; polybar -r example &
sleep 5 && st &
